version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/workdir
        steps:
            - checkout
            - run:
                name: Get current site
                working_directory: ~/workdir
                command: git clone -q --depth 1 https://${BLOG_GITHUB_TOKEN}@github.com/savetheales/blog.git
            - run:
                name: Generate site
                working_directory: ~/workdir
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git init
                    git config user.email "ales.puchilo@gmail.com"
                    git config user.name "Ales Puchilo"
                    git add .
                    git push -q -f https://${BLOG_GITHUB_TOKEN}@github.com/savetheales/blog.git master:gh-pages

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master