# version: 2.0

# jobs:
#     build:
#         docker:
#             - image: felicianotech/docker-hugo:latest
#         working_directory: ~/workdir
#         steps:
#             - checkout
#             - run:
#                 name: Get current site
#                 working_directory: ~/
#                 command: git clone -q --depth 1 https://${BLOG_GITHUB_TOKEN}@github.com/savetheales/blog.git
#             - run:
#                 name: Generate site
#                 working_directory: ~/blog
#                 command: HUGO_ENV=production hugo -d ~/public
#             - deploy:
#                 name: Deploy to Github Pages
#                 working_directory: ~/public
#                 command: |
#                     ls
#                     git config user.email "ales.puchilo@gmail.com"
#                     git config user.name "Ales Puchilo"
#                     git init
#                     git add .
#                     git commit --allow-empty -m "Trigger deployment"
#                     gh-pages --dotfiles --message "[skip ci] Updates" --dist public

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master

version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/blog
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: HUGO_ENV=production hugo -F -v -d $HUGO_BUILD_DIR
      - persist_to_workspace:
          root: public
          paths: .
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: public
      - run:
          name: Disable jekyll builds
          command: touch public/.nojekyll
    #   - run:
    #       name: Custom Domain
    #       command: echo "example.domain" > public/CNAME
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ales.puchilo@gmail.com"
            git config user.name "Ales Puchilo"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist public